version: '2'
services:
    app:
        build: .
        command: bash -c 'env | sort | grep PORT && /app/image/bin/wait-for-linked-services'
        volumes:
            - .:/app/image/bin
        environment:
            #- DEBUG=1
            # Services
            - REDIS_1_PORT=tcp://redis:6379
            - POSTGRES_1_PORT=tcp://postgres:5432
            - EXISTS_0_PORT=exists:///dev/null
            - FILE_0_PORT=file:///bin/bash
            - SLEEP_0_PORT=sleep://5
            - FAILFILE_0_PORT=file:///tmp/nope

    redis:
        image: redis

    postgres:
        image: postgres

